{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9ddd08e1-6df5-4118-bfc8-83b1b16143b5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model loaded successfully.\n",
      "{\n",
      "    \"word\": \"cry\",\n",
      "    \"confidence\": 0.8897\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from pathlib import Path\n",
    "import json\n",
    "\n",
    "# ==============================\n",
    "# CONFIG\n",
    "# ==============================\n",
    "\n",
    "MODEL_PATH = r\"tcn_best_cpu_3rdcode.pth\"\n",
    "LABEL_PATH = r\"label_encoder_3rdcode.npy\"\n",
    "\n",
    "DEVICE = \"cpu\"\n",
    "TARGET_FRAMES = 157\n",
    "FEATURE_DIM = 438\n",
    "\n",
    "# ==============================\n",
    "# MODEL DEFINITION\n",
    "# ==============================\n",
    "\n",
    "class TemporalBlock(nn.Module):\n",
    "    def __init__(self, ic, oc, d):\n",
    "        super().__init__()\n",
    "        self.net = nn.Sequential(\n",
    "            nn.Conv1d(ic, oc, 3, padding=d, dilation=d),\n",
    "            nn.BatchNorm1d(oc),\n",
    "            nn.ReLU(),\n",
    "            nn.Conv1d(oc, oc, 3, padding=d, dilation=d),\n",
    "            nn.BatchNorm1d(oc),\n",
    "            nn.ReLU(),\n",
    "        )\n",
    "        self.res = nn.Conv1d(ic, oc, 1) if ic != oc else nn.Identity()\n",
    "\n",
    "    def forward(self, x):\n",
    "        y = self.net(x)\n",
    "        y = y[..., :x.size(2)]\n",
    "        return y + self.res(x)\n",
    "\n",
    "class TCN(nn.Module):\n",
    "    def __init__(self, num_classes):\n",
    "        super().__init__()\n",
    "        chans = [192, 192, 192, 192]\n",
    "        layers = []\n",
    "        for i, c in enumerate(chans):\n",
    "            layers.append(\n",
    "                TemporalBlock(\n",
    "                    FEATURE_DIM if i == 0 else chans[i-1],\n",
    "                    c, 2 ** i\n",
    "                )\n",
    "            )\n",
    "        self.tcn = nn.Sequential(*layers)\n",
    "        self.fc = nn.Linear(chans[-1], num_classes)\n",
    "\n",
    "    def masked_pool(self, x, m):\n",
    "        m = m.unsqueeze(1)\n",
    "        return (x * m).sum(2) / (m.sum(2) + 1e-6)\n",
    "\n",
    "    def forward(self, x, m):\n",
    "        x = self.tcn(x)\n",
    "        x = self.masked_pool(x, m)\n",
    "        return self.fc(x)\n",
    "\n",
    "# ==============================\n",
    "# LOAD MODEL\n",
    "# ==============================\n",
    "\n",
    "LABELS = np.load(LABEL_PATH)\n",
    "model = TCN(len(LABELS)).to(DEVICE)\n",
    "model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))\n",
    "model.eval()\n",
    "\n",
    "print(\"Model loaded successfully.\")\n",
    "\n",
    "# ==============================\n",
    "# PREDICT FUNCTION\n",
    "# ==============================\n",
    "\n",
    "def predict(sample_path, top_k=5):\n",
    "    x = np.load(sample_path)\n",
    "    m = np.load(sample_path.replace(\".npy\", \"_mask.npy\"))\n",
    "\n",
    "    if x.shape != (TARGET_FRAMES, FEATURE_DIM):\n",
    "        raise ValueError(\"Input shape mismatch.\")\n",
    "\n",
    "    x = torch.from_numpy(x).float().unsqueeze(0).transpose(1, 2)\n",
    "    m = torch.from_numpy(m).float().unsqueeze(0)\n",
    "\n",
    "    with torch.no_grad():\n",
    "        logits = model(x, m)\n",
    "        probs = torch.softmax(logits, dim=1)\n",
    "\n",
    "    topk = torch.topk(probs, k=top_k)\n",
    "    indices = topk.indices[0].numpy()\n",
    "    confidences = topk.values[0].numpy()\n",
    "\n",
    "    results = []\n",
    "    for idx, conf in zip(indices, confidences):\n",
    "        results.append((LABELS[idx], float(conf)))\n",
    "\n",
    "    return results\n",
    "# ==============================\n",
    "# RUN\n",
    "# ==============================\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "\n",
    "    sample = r\"E:\\ASL_Citizen\\NEW\\Top_Classes_Landmarks_Preprocessed\\cry_3.npy\"\n",
    "\n",
    "    predictions = predict(sample, top_k=1)\n",
    "\n",
    "    label, conf = predictions[0]\n",
    "\n",
    "    output = {\n",
    "        \"word\": str(label),\n",
    "        \"confidence\": round(float(conf), 4)\n",
    "    }\n",
    "\n",
    "    print(json.dumps(output, indent=4))\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aa5fd6a9-aee5-40cc-b5dc-34ecd37b9423",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10 (venv310)",
   "language": "python",
   "name": "venv310"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
